name: End-to-end tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn && yarn playwright install --with-deps

      - name: Run end-to-end tests
        run: yarn test:e2e

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports
          path: reports/
          retention-days: 7
